name: MySmaller Tailscale Build Pipeline

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ build-tailscale ]

permissions:
  contents: read

env:
  SOFTWARE_NAME: "Tailscale"
  REPO: "tailscale/tailscale"
  REPO_SMALL: "GuNanOvO/openwrt-tailscale"
  REPO_SMALL_NAME: "openwrt-tailscale"
  REPO_SMALL_OWNER: "GuNanOvO"
  ARTIFACT_DIR: "artifacts"
  OPENWRT_IPK_SDK: "24.10.4"
  OPENWRT_APK_SDK: "25.12.0"
  SKIP_TARGETS_24: "riscv64_generic" 
  SKIP_TARGETS_25: "mips_4kec riscv64_riscv64" 

jobs:
  prepare:
    name: Prepare UPX and Go
    runs-on: ubuntu-latest
    outputs:
      upx_ver: ${{ steps.check_upx.outputs.upx_ver }}
      go_version: ${{ steps.check_go.outputs.go_version }}
    steps:
      # ----------------- UPX -----------------
      - name: Check Latest UPX Version
        id: check_upx
        run: |
          UPX_TAG=$(curl -s https://api.github.com/repos/upx/upx/releases/latest \

            | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "UPX_TAG=$UPX_TAG" >> "$GITHUB_ENV"
          UPX_VER="${UPX_TAG#v}"
          echo "Detected UPX Version: $UPX_VER"
          echo "upx_ver=$UPX_VER" >> "$GITHUB_OUTPUT"
          echo "UPX_VER=$UPX_VER" >> "$GITHUB_ENV"

      - name: Restore UPX Cache
        id: cache_upx
        uses: actions/cache@v5
        with:
          path: upx
          key: upx-linux-amd64-${{ steps.check_upx.outputs.upx_ver }}

      - name: Prepare UPX
        if: steps.cache_upx.outputs.cache-hit != 'true'
        run: |
          UPX_URL="https://github.com/upx/upx/releases/download/$UPX_TAG/upx-${UPX_VER}-amd64_linux.tar.xz"
          echo "Downloading UPX from: $UPX_URL"
          mkdir -p upx
          curl -L -o upx.tar.xz "$UPX_URL"
          tar -xf upx.tar.xz -C upx --strip-components=1
          chmod +x upx/upx
          rm -f upx.tar.xz

      - name: Save UPX Cache
        if: steps.cache_upx.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: upx
          key: upx-linux-amd64-${{ steps.check_upx.outputs.upx_ver }}

      # ----------------- Go -----------------
      - name: Check Latest Go Version
        id: check_go
        run: |
          GO_TAG=$(curl -s https://go.dev/VERSION?m=text | head -1)
          echo "GO_TAG=$GO_TAG" >> "$GITHUB_ENV"
          GO_VER="${GO_TAG#go}"
          echo "Detected Go Version: $GO_VER"
          echo "go_version=$GO_VER" >> "$GITHUB_OUTPUT"
          echo "GO_VERSION=$GO_VER" >> "$GITHUB_ENV"

      - name: Restore Go Cache
        id: cache_go
        uses: actions/cache@v5
        with:
          path: go
          key: go-linux-amd64-${{ steps.check_go.outputs.go_version }}

      - name: Prepare Go
        if: steps.cache_go.outputs.cache-hit != 'true'
        run: |
          GO_OS=linux
          GO_ARCH=amd64
          GO_URL="https://go.dev/dl/$GO_TAG.$GO_OS-$GO_ARCH.tar.gz"
          echo "Downloading Go from: $GO_URL"
          mkdir -p go
          curl -L -o go.tar.gz "$GO_URL"
          tar -C go -xzf go.tar.gz --strip-components=1
          rm -f go.tar.gz

      - name: Save Go Cache
        if: steps.cache_go.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: go
          key: go-linux-amd64-${{ steps.check_go.outputs.go_version }}

  build:
    name: Build for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_build_version.outputs.version }}
      date: ${{ steps.get_build_date.outputs.date }}
    needs: prepare
    strategy:
      matrix:
        platform:
          - 'aarch64_generic'
          - 'x86_64'
      fail-fast: true

    steps:
      # PREPARE TOOLS
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: main
          path: repo

      - name: Set Build Version
        id: get_build_version
        run: |
          VERSION=$(sed -n 's/^PKG_VERSION:=\(.*\)/\1/p' repo/package/tailscale/Makefile | tr -d '[:space:]')
          sed -i 's|.*\/etc\/init\.d\/tailscale.*||g' repo/package/tailscale/Makefile
          sed -i 's|.*\/etc\/config\/tailscale.*||g' repo/package/tailscale/Makefile
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Parsed version: $VERSION"

      - name: Set Build Timestamp
        id: get_build_date
        run: |
          echo "date=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Prepare Build Scripts, Package Files, and Keys
        env:
          USIGN_SECRET_KEY_B64: ${{ secrets.USIGN_SECRET_KEY_B64 }}
          RSA_SECRET_KEY_B64: ${{ secrets.RSA_SECRET_KEY_B64 }}
        run: |
          mkdir build_scripts
          cp repo/build_scripts/*.sh build_scripts/

          mkdir tailscale
          cp -r repo/package/tailscale/. tailscale/

          mkdir keys
          echo "$USIGN_SECRET_KEY_B64" | base64 -d > keys/key-build.sec || echo "No USIGN key"
          echo "$RSA_SECRET_KEY_B64" | base64 -d > keys/key-build.rsa || echo "No RSA key"

      - name: Restore UPX Cache
        uses: actions/cache@v5
        id: cache-upx
        with:
          path: upx
          key: upx-linux-amd64-${{ needs.prepare.outputs.upx_ver }}

      - name: Restore Go Cache
        uses: actions/cache@v5
        id: cache-go
        with:
          path: go
          key: go-linux-amd64-${{ needs.prepare.outputs.go_version }}

      - name: Pull OpenWRT 24.10 SDK Docker Image
        run: |
          if echo "${{ env.SKIP_TARGETS_24 }}" | grep -qw "${{ matrix.platform }}"; then
            echo "Skipping pull of OpenWRT 24.10 SDK for ${{ matrix.platform }} due to unsupported target."
          else
            docker pull ghcr.io/openwrt/sdk:${{ matrix.platform }}-V${{ env.OPENWRT_IPK_SDK }}
          fi

      - name: Pull OpenWRT 25.12 SDK Docker Image
        run: |
          if echo "${{ env.SKIP_TARGETS_25 }}" | grep -qw "${{ matrix.platform }}"; then
            echo "Skipping pull of OpenWRT 25.12 SDK for ${{ matrix.platform }} due to unsupported target."
          else
            docker pull ghcr.io/openwrt/sdk:${{ matrix.platform }}-V${{ env.OPENWRT_ADDR_SDK || env.OPENWRT_APK_SDK }}
          fi

      # BUILD PACKAGES
      - name: Prepare Directories and Permissions
        run: |
          mkdir -p bin
          mkdir -p "${{ env.ARTIFACT_DIR }}"
          chmod -R 777 bin || true

      - name: Build with OpenWRT 24.10 SDK Docker
        run: |
          if echo "${{ env.SKIP_TARGETS_24 }}" | grep -qw "${{ matrix.platform }}"; then
            echo "Skipping build with OpenWRT 24.10 SDK for ${{ matrix.platform }} due to unsupported target."
          else
            docker run --rm \
              -v "$(pwd)/bin:/builder/bin:z" \
              -v "$(pwd)/build_scripts:/builder/build_scripts:ro,z" \
              -v "$(pwd)/tailscale:/builder/tailscale:ro,z" \
              -v "$(pwd)/keys:/builder/keys:ro,z" \
              -v "$(pwd)/upx:/builder/upx:ro,z" \
              -v "$(pwd)/go:/builder/go:ro,z" \
              -e TERM=xterm \
              -e FORCE=1 \
              ghcr.io/openwrt/sdk:${{ matrix.platform }}-V${{ env.OPENWRT_IPK_SDK }} \
              bash /builder/build_scripts/build_ipk.sh "${{ steps.get_build_version.outputs.version }}" "${{ matrix.platform }}"
          fi

      - name: Build with OpenWRT 25.12 SDK Docker
        run: |
          if echo "${{ env.SKIP_TARGETS_25 }}" | grep -qw "${{ matrix.platform }}"; then
            echo "Skipping build with OpenWRT 25.12 SDK for ${{ matrix.platform }} due to unsupported target."
          else
            docker run --rm \
              -v "$(pwd)/bin:/builder/bin:z" \
              -v "$(pwd)/build_scripts:/builder/build_scripts:ro,z" \
              -v "$(pwd)/tailscale:/builder/tailscale:ro,z" \
              -v "$(pwd)/keys:/builder/keys:ro,z" \
              -v "$(pwd)/upx:/builder/upx:ro,z" \
              -v "$(pwd)/go:/builder/go:ro,z" \
              -e TERM=xterm \
              -e FORCE=1 \
              ghcr.io/openwrt/sdk:${{ matrix.platform }}-V${{ env.OPENWRT_APK_SDK }} \
              bash /builder/build_scripts/build_apk.sh "${{ steps.get_build_version.outputs.version }}" "${{ matrix.platform }}"
          fi

      # ARTIFACT COLLECT & UPLOAD
      - name: Organize Artifacts
        run: |
          find bin/ -type f \( -name "*.ipk" -o -name "*.apk" \) -exec cp {} "${{ env.ARTIFACT_DIR }}/" \;
          echo "Organized artifacts:"
          ls -la "${{ env.ARTIFACT_DIR }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: tailscale-${{ matrix.platform }}
          path: ${{ env.ARTIFACT_DIR }}/*
